const Map<String, Map<String, String>> weatherDescriptions = {
  "cielo despejado": {"es": "cielo despejado", "en": "clear sky"},
  "pocas nubes": {"es": "pocas nubes", "en": "few clouds"},
  "nubes dispersas": {"es": "pubes dispersas", "en": "scattered clouds"},
  "muy nuboso": {"es": "muy nuboso", "en": "very cloudy"},
  "nubes": {"es": "nubes", "en": "clouds"},
  "algo de nubes": {"es": "algo de nubes", "en": "some clouds"},
  "nublado": {"es": "nublado", "en": "broken clouds"},
  "cielo cubierto": {"es": "cielo cubierto", "en": "overcast clouds"},
  "chubascos": {"es": "chubascos", "en": "shower rain"},
  "lluvia ligera": {"es": "lluvia ligera", "en": "light rain"},
  "lluvia moderada": {"es": "lluvia moderada", "en": "moderate rain"},
  "lluvia intensa": {"es": "lluvia intensa", "en": "heavy rain"},
  "lluvia muy intensa": {"es": "lluvia muy intensa", "en": "very heavy rain"},
  "lluvia extrema": {"es": "lluvia extrema", "en": "extreme rain"},
  "lluvia helada": {"es": "lluvia helada", "en": "freezing rain"},
  "chubascos ligeros": {"es": "chubascos ligeros", "en": "light shower rain"},
  "chubascos fuertes": {"es": "chubascos fuertes", "en": "heavy shower rain"},
  "chubascos irregulares": {"es": "chubascos irregulares", "en": "ragged shower rain"},
  "tormenta": {"es": "tormenta", "en": "thunderstorm"},
  "tormenta con lluvia ligera": {"es": "tormenta con lluvia ligera", "en": "thunderstorm with light rain"},
  "tormenta con lluvia": {"es": "tormenta con lluvia", "en": "thunderstorm with rain"},
  "tormenta con lluvia intensa": {"es": "tormenta con lluvia intensa", "en": "thunderstorm with heavy rain"},
  "nieve ligera": {"es": "nieve ligera", "en": "light snow"},
  "nieve": {"es": "nieve", "en": "snow"},
  "nieve intensa": {"es": "nieve intensa", "en": "heavy snow"},
  "aguanieve": {"es": "aguanieve", "en": "sleet"},
  "aguanieve ligera": {"es": "aguanieve ligera", "en": "light shower sleet"},
  "lluvia y nieve ligera": {"es": "lluvia y nieve ligera", "en": "light rain and snow"},
  "lluvia y nieve": {"es": "lluvia y nieve", "en": "rain and snow"},
  "chubascos de nieve ligera": {"es": "chubascos de nieve ligera", "en": "light shower snow"},
  "chubascos de nieve": {"es": "chubascos de nieve", "en": "shower snow"},
  "chubascos de nieve intensa": {"es": "chubascos de nieve intensa", "en": "heavy shower snow"},
  "niebla": {"es": "niebla", "en": "mist"},
  "humo": {"es": "humo", "en": "smoke"},
  "calina": {"es": "calina", "en": "haze"},
  "torbellinos de arena/polvo": {"es": "torbellinos de arena/polvo", "en": "sand/dust whirls"},
  "niebla densa": {"es": "niebla densa", "en": "fog"},
  "arena": {"es": "arena", "en": "aand"},
  "polvo": {"es": "polvo", "en": "dust"},
  "ceniza volcánica": {"es": "ceniza volcánica", "en": "volcanic ash"},
  "ráfagas": {"es": "táfagas", "en": "squalls"},
  "tornado": {"es": "tornado", "en": "tornado"},
  "cielo claro": {"es": "cielo claro", "en": "clear sky"}
};
